#!/bin/sh -eu

fqdn="$(hostname).retroska"

# Generate passwords if not provided
if test -z "${RETRO_IRC_PW+x}"; then
    export RETRO_IRC_PW=`pwgen -B 8`
fi

# Prepare pub directory
mkdir -p /mnt/srv/pub /mnt/srv/incoming /mnt/conf
rmdir /srv/ftp || true
chmod 0775 /mnt/srv/pub
chmod 0777 /mnt/srv/incoming

# Samba Workgroup
cat >/etc/samba/smb.user.conf <<EOF
[global]
workgroup = ${RETRO_WORKGROUP-WORKGROUP}
EOF

# Create initial banner used by FTP and many others
if ! test -e /mnt/conf/banner.txt; then
    cat >/mnt/conf/banner.txt <<EOF
Welcome to $fqdn!

The server is operated by ${RETRO_ADMIN-Anonymous}
and it's located in ${RETRO_LOCATION-unknown location}.

To contact the admin, send e-mail to ${RETRO_EMAIL-unknown@example.com}

EOF
fi

# IRC configuration
mkdir -p /etc/ngircd/conf.d
cat >/etc/ngircd/conf.d/user.conf <<EOF
[Global]
Name = $fqdn
AdminInfo1 = ${RETRO_ADMIN-Anonymous}
AdminInfo2 = ${RETRO_LOCATION-Unknown}
AdminEMail = ${RETRO_EMAIL-unknown@example.com}
Info = Retroska IRC server operated by ${RETRO_ADMIN-Anonymous}

[Operator]
# ID of the operator (may be different of the nickname)
Name = operator
Password = ${RETRO_IRC_PW}
EOF

# DHCP static leases
if ! test -e /mnt/conf/dhcp-static.conf; then
    cat >/mnt/conf/dhcp-static.conf <<EOF
#mac,ip,hostname
EOF
fi

# Generate summary of passwords
cat >/root/credentials.txt <<EOF
Initial passwords:

IRC: operator / ${RETRO_IRC_PW}
EOF

# Remove me after running
rm "$0"
