#!/bin/sh -eu

# Prepare pub directory
mkdir -p /mnt/srv/pub /mnt/srv/incoming /mnt/conf
rmdir /srv/ftp || true
chmod 0775 /mnt/srv/pub
chmod 0777 /mnt/srv/incoming

# Samba Workgroup
cat >/etc/samba/smb.user.conf <<EOF
[global]
workgroup = ${RETRO_WORKGROUP-WORKGROUP}
EOF

# Create initial banner
if ! test -e /mnt/conf/banner.txt; then
    echo "Welcome to $(hostname)" >/mnt/conf/banner.txt
fi

#if test "${RETRO_WORKGROUP+x}"; then

# Remove me after running
rm "$0"
