#!/bin/sh -eu

# Prepare pub directory
mkdir -p /mnt/srv/pub /mnt/srv/incoming
chmod 0775 /mnt/srv/pub
chmod 0777 /mnt/srv/incoming

# Samba Workgroup
cat >/etc/samba/smb.user.conf <<EOF
[global]
workgroup = ${RETRO_WORKGROUP-WORKGROUP}
EOF

#if test "${RETRO_WORKGROUP+x}"; then

# Remove me after running
rm "$0"
