#!/bin/sh -eu
#
# Run from systemd.
#
# This intended to be run on upkeep_permissions startup, bulk fixing
# permissions of pre-existing files.

# Directory permissions
find "$DIR" -mindepth 1 -type d -print0 | xargs -r0 chmod "$WANTED_PERM_DIR"
# File permissions
find "$DIR" -mindepth 1 -type f -print0 | xargs -r0 chmod "$WANTED_PERM_FILE"
# Ownership
find "$DIR" -mindepth 1 -type f,d -print0 | xargs -r0 chown "$WANTED_OWNER"
