#!/bin/sh -eu
#
# Run from systemd, passing WANTED_PERM_DIR, WANTED_PERM_FILE, and
# WANTED_OWNER to fix_file_permission.
#
# If the file name contains newline (\n) this fails due to the
# limitation in inotifywait.

inotifywait -m --format %w%f -e create -e moved_to -r "$DIR" | xargs -n 1 -d '\n' /opt/fix_file_permission
